gameworld: bw_gameworld
presetworld: presets
creature_spawn: false
generator:
   splitted:
      panels: 5
      per: 10
gameplacement:
   gap: 500
   y-position: 70
   z-position: 500 
death_y_offset: 20
death_timeout: 80