stats: YAML
mysql:
   host: 127.0.0.1
   port: 3306
   user: bedwarsunlimited
   database: bedwarsunlimited
   password: password
gameworld: bw_gameworld
presetworld: presets
creature_spawn: false
group_command: true
leave_command: true
worlds:
   allow_rain: false
   default_time: 1000
   presets_time: 1000
   game_time: 1000
generator:
   splitted:
      panels: 5
      per: 10
gameplacement:
   gap: 500
   y-position: 70
   z-position: 500
game:
   leaveitem_slot: 8
   teamselector_slot: 0
   spectator_out_fly: 50
   no_drop:
     - WEB
     - GLOWSTONE
     - STAINED_GLASS
lobby:
   respawn_y: 40
   challenger:
      enabled: true
      slot: 0
      cooldown: 3
   gamelist:
      enabled: true
      slot: 1
challenger:
   lobby_time: 5
defaultsettings:
   fixed_teams: false
   allow_join: true
   allow_spectate: true
   lobby_leave: NORMAL
   min_players: 2
   max_players: 0
   min_lobby_countdown: 10
   game_end: 36000
   ending_countdown: 10   
   spawn_protection: 1
death_y_offset: 20
death_timeout: 80