name: BedwarsUnlimited
version: 1.0.0 INDEV
description: BedwarsUnlimited Plugin by MeLays
author: MeLays
website: http://melays.de/
main: de.melays.bwunlimited.Main
softdepend: [StatsAPI]
commands:
  bw:
    description: Manage the BedwarsUnlimited Plugin
    aliases: [bedwars , bwunlimited , bedwarsunlimited]
    usage: /bw
  group:
    description: BedwarsUnlimited Groups
    aliases: [group,groups,party]
    usage: /group