name: BedwarsUnlimited
version: 1.0.1 BETA
description: BedwarsUnlimited Plugin by MeLays
author: MeLays
website: http://melays.de/
main: de.melays.bwunlimited.Main
softdepend: [StatsAPI,Vault,SymptaFriends]
commands:
  bw:
    description: Manage the BedwarsUnlimited Plugin
    aliases: [bedwars , bwunlimited , bedwarsunlimited]
    usage: /bw help
  group:
    description: BedwarsUnlimited Groups
    aliases: [group,groups,party,p,g]
    usage: /group help
  leave:
    description: BedwarsUnlimited Leave
    aliases: [l,hub,lobby]
    usage: /leave
  start:
    description: BedwarsUnlimited Start
    aliases: []
    usage: /start
  spectate:
    description: BedwarsUnlimited Spectate
    aliases: []
    usage: /spectate