gamelobby:
  inventory:
    teamselector:
      name: "&6Team selector"
      type: STAINED_GLASS_PANE
      display: "&7Team: %color%%displayname% &7(%current%/%max%)"
      lore: "%color%Players:"
      lore_selected: "%color%>> &lPlayers %color%<<:"
      lore_empty: "  %color%-  &7&oNo players"
      playerlist: "  %color%-  %color%%player%"
  title:
    title_3: "&1&l»&9»» &c➌ &9««&1&l«"
    title_2: "&9»&1&l»&9» &e➋ &9«&1&l«&9«"
    title_1: "&9»»&1&l»&r &2➊ &1&l«&9««"
    title_0: "&9»»&1&l»&r &aGO! &1&l«&9««"
    sub_title: "&9%cluster_display%"
game:
  tab:
    format_prefix: "%color%"
    format_suffix: " &8[%color%%display%&8]"
    unknown_format_prefix: "&7"
    unknown_format_suffix: ""
    spectator_format_prefix: "&8&o"
    spectator_format_suffix: ""
  scoreboard:
    title: "&9Bedwars"
    timer:
      divider: "&8:"
      minutes: "   &7%minutes%"
      seconds: "&7%seconds%"
    symbol: "   ❤ &8| "
    color_alive: "&c"
    color_dead: "&8"
    symbol_out: "   &8✘ &8| "
    content:
      - " "
      - "&8&l» &9Time &9Remaining:"
      - time-line
      - "  "
      - "&8&l» &9Teams:"
      - team-lines
      - "   "
  titles:
    bed: "&cBed destroyed"
    bed_sub: "&4Your teams bed has been destroyed!"
    win: "%color%%display%"
    win_sub: "&awon the game!"
tab:
  header:
    - ""
    - "&9BW&1\u221E &8- &7Server"
    - ""
  footer:
    - ""
lobby:
  tab:
    prefix: "&7%player_prefix%"
    suffix: "%player_suffix%"
  inventory:
    choosemap:
      title: "&a%p%&7 Players &0(&a%page%&0/&c%max%&0)"
      map:
        title: "&c%display%"
        title_selected: "&2&l>> &a%display% &2&l<<"
        lore:
          - "&cClick to choose this map"
        lore_selected:
          - "&aSelected"
shop:
  type: villager
  display: "&6Dealer"
sign:
  template:
    empty:
      1: "&8» &8&lBedwars &8«"
      2: "&8%current%&7/&2%max%"
      3: "&8Empty"
      4: "&8%cluster%-%id%"
    default:
      1: "&8» &9&lBedwars &8«"
      2: "&a%current%&8/&2%max%"
      3: "&9Lobby"
      4: "&1%cluster%-%id%"
    full:
      1: "&8» &c&lBedwars &8«"
      2: "&c%current%&8/&c%max%"
      3: "&cVoll"
      4: "&1%cluster%-%id%"